### ISSUE TITLE
[Alias] Add Forwarding Address

### ISSUE THREAD

**Issue by Ellobo16** [Telios-org/rn-mobile-client#101]
### Description

When I attempt to add a forwarding address, the app allows me to perform the action, but it does not save the address on the alias.

### Steps to reproduce

1. Either add a forwarding address to a new alias or edit an alias
2. Type in a 'Forwarding Address
3. Select Done

### Expected behavior

- Forwarding address should display

**Comment by vitalikgriza** [comment]
@Ellobo16 try please to check the email(green checkbox) in the modal before press done

**Comment by Ellobo16** [comment]
@vitalikgriza confirmed! Thank you!
