### ISSUE TITLE
[Account Sync] Syncing screen needs an activity indicator

### ISSUE THREAD

**Issue by hexadecible** [Telios-org/rn-mobile-client#14]
When I start syncing my account, I see the loading status as 0%, and then it is immediately completed without seeing any other indicators. This almost felt as if it froze. Instead of the 0%, we should show a loading indicator and when the percentage is > 0%, then replace the loading icon with the percent loaded.

**Comment by Ellobo16** [comment]
@vitalikgriza When I sync my account, it succeeds. However, I don't see the progress/activity indicator specified in the ticket. Is this doable with the sync?

**Comment by vitalikgriza** [comment]
@Ellobo16, it's because of the size of drive disk is too small. I see sync indicator for a fraction of second when I have more then 30 emails in my inbox
