### ISSUE TITLE
Selecting email messages crashes the app

### ISSUE THREAD

**Issue by hexadecible** [Telios-org/rn-mobile-client#15]
I'm not sure if this is related, but after syncing an account, I then synced an email from the remote peer and selected the new message on mobile. This immediately crashed the app.

**Comment by vitalikgriza** [comment]
@suleymancelikel could you please check that, I think you mention that you fixed it

**Comment by suleymancelikel** [comment]
Hello, fixed the bug of seeing the details of the selected new message. After this [PR](https://github.com/Telios-org/rn-mobile-client/pull/17) is merged we can test this specific "syncing an account" case. Thanks

**Comment by Ellobo16** [comment]
@vitalikgriza @suleymancelikel 

I could not test syncing on the latest TestFlight build: 

![15-Syncing Mobile Devices](https://user-images.githubusercontent.com/114693640/199273850-4cee261a-aa84-4300-a05d-a7e6cebc6e95.jpeg)
