### ISSUE TITLE
Aliases - Create multiple namespaces

### ISSUE THREAD

**Issue by hexadecible** [Telios-org/rn-mobile-client#18]
In the current mobile version, users can only create one alias namespace. We should allow users to create multiple aliases if their current plan allows it (API will return a readable error if users try creating more than their plan allows).

- [ ] Create the ability to add multiple alias namespaces in the mobile UI
- [ ] Show multiple alias namespaces in the alias manage screen
- [ ] When new alias addresses are added to namespaces, they should roll up underneath their corresponding alias namespace to create an association.

**Desktop example of the Alias Management screen:**
![Screen Shot 2022-07-14 at 12 13 57 PM](https://user-images.githubusercontent.com/63071090/179032237-a0444976-3026-4eca-8d33-9d568b25526c.png)

**Comment by vitalikgriza** [comment]
Do we have api to check current user's plan?

**Comment by vitalikgriza** [comment]
Added also alias info screen
