### ISSUE TITLE
Alias - Associate aliases to namespaces with a multi-select element

### ISSUE THREAD

**Issue by hexadecible** [Telios-org/rn-mobile-client#19]
When creating a new alias, users will need a dropdown to choose which namespace they would like their alias to be associated with. Right now it's hard coded to only a single alias namespace.

Desktop example:
![Screen Shot 2022-07-14 at 12 40 54 PM](https://user-images.githubusercontent.com/63071090/179034009-99189802-2c90-4ba9-a355-67a87722babe.png)
![Screen Shot 2022-07-14 at 12 41 16 PM](https://user-images.githubusercontent.com/63071090/179034018-57f06df9-687a-471c-9bd9-8bfafb745379.png)

**Comment by vitalikgriza** [comment]
No need to add multi select element, namespaces will be displayed in a dropdown element
