### ISSUE TITLE
Alias - Add a UI heirarchy for multilpe namespaces and aliases in the mobile sidebar

### ISSUE THREAD

**Issue by hexadecible** [Telios-org/rn-mobile-client#20]
- [x] Display a row for each alias namespace
- [x] Allow each alias namespace row to be expanded
- [x] Show the total unread email count for each namespace
- [x] When the namespace row is expanded, show all aliases registered under this namespace
- [x] Show the total unread email count for each alias

![Screen Shot 2022-07-14 at 12 46 20 PM](https://user-images.githubusercontent.com/63071090/179035157-fc17c0c3-4c9d-4dae-b354-37eef719ff12.png)

**Comment by vitalikgriza** [comment]
What should happen when alias row is pressed?
From example screen "Inbox" tab is selected, is it related to aliases?
