### ISSUE TITLE
Aliases - Add the ability to generate random aliases

### ISSUE THREAD

**Issue by hexadecible** [Telios-org/rn-mobile-client#23]
Add the ability for users to generate random aliases that are not tied to namespaces.

A random alias can be generated by a UID, random 3 words, or an alphanumeric string.

- [x] Add the option to generate random UID alias. UID should have the format **63179361.41a9.4907.907e.053fb2829fd1** where a dash (-) is replaced with a period (.).
- [x] Add the option to generate random 3-word alias. The format should have a period between each word **enough.few.winter**.
- [x] Add the option to generate a random alphanumeric string. The string should be random 12 characters long using **abcdefghijklmnopqrstuvwxyz1234567890**
- [x] Show random aliases in the sidebar at the bottom of user-generated namespaces. All random aliases will collapse underneath the random alias accordion.
- [x] Use a different icon (same as desktop) for the random alias accordion. Random aliases underneath accordion will use the **@** icon, similar to aliases underneath namespaces.

Desktop examples:
![Screen Shot 2022-07-25 at 12 46 23 PM](https://user-images.githubusercontent.com/63071090/180831396-b47459d7-16aa-471a-bf32-515d96449aeb.png)

![Screen Shot 2022-07-25 at 12 46 53 PM](https://user-images.githubusercontent.com/63071090/180831497-53b32903-001c-4172-a4a7-77117c2a4d75.png)

**Comment by Ellobo16** [comment]
**11/01/2022 Testing Results**

Pass
