### ISSUE TITLE
Store normalized aliases using entity adapter

### ISSUE THREAD

**Issue by vitalikgriza** [Telios-org/rn-mobile-client#31]
Currently aliases are stored as simple list. Need to normalize aliases to optimise redux updates, using createEntityAdapter from redux/toolkit
Also fix getAliases for updating single entity(getAlias), for now getAliases returns all aliases even namespaceKey is given, that will be fixed

**Comment by Ellobo16** [comment]
@vitalikgriza I suspect this is more of a 'behind the scenes' ticket. Aliases are being pulled back and rendered appropriately. From a user experience perspective, this ticket passes.
