### ISSUE TITLE
Add user profile screen

### ISSUE THREAD

**Issue by vitalikgriza** [Telios-org/rn-mobile-client#36]
ProfileScreen - this screen exists, but has basically zero functionality currently. It has a 'log out' button, but that's it
![Untitled](https://user-images.githubusercontent.com/42895774/183502149-60727550-9502-4cbf-8f4c-b59a14dd9ae2.png)

**Comment by hexadecible** [comment]
- [x] Add user avatar. If no user avatar exists, then use the initials of the first and last name. ie Phillip Fry would be FF. The initials should be inside a circle element. The background for this circle is dynamically generated based on the user's email (see example code for how we did this on desktop)
- [x] Allow the avatar to be editable. Users should have the option to upload their own avatar if none exists.
- [x] Display first and last name. If no first and last name exist, allow the user to add these via some sort of edit functionality. This wasn't originally added to figma so please use your best judgment on how we should allow the user to edit or add a first and last name here.
- [x] Display email address underneath first and last name
- [x] Display which plan this user has underneath their email address. Plans are Basic, Starter, Premium, Ultimate, and Early Adopter. This should be on the account object in Redux.
- [x] Create a navigation item named "Contacts" that directs the user to a screen where they can manage their contacts
- [x] Create a navigation item named "Plan & Billing" that directs the user to a screen where they can manage their plan and billing preferences
- [x] Create a navigation item named "Security" that directs the user to a screen where they can view their public and private keys.
- [x] Create a navigation item named "Log Out" that signs the user out of their account and returns them to the main login screen (This should already be there)

&nbsp;

**Dynamically Generated Avatar:**
Note: We should probably create a reusable component here so we can reuse this on the different inbox list views.
![Screen Shot 2022-08-12 at 9 25 37 AM](https://user-images.githubusercontent.com/63071090/184363161-688920a4-11d8-4d74-a0ed-9a08fca45364.png)

```javascript
function stringToHslColor(str, s, l) {
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    hash = str.charCodeAt(i) + ((hash << 5) - hash);
  }

  const h = hash % 360;
  return `hsl(${h}, ${s}%, ${l}%)`;
}

<span
    className="inline-flex items-center justify-center h-32 w-32 rounded-full ring-4 ring-white"
    style={{backgroundColor: stringToHslColor(profile.email, 50, 50)}}
  >
```

&nbsp;

**Avatar Image should be uploaded as base64 encoded data to the Account document in the local database.**

```javascript
const payload = {
  accountId: '62f562e9641d5bff26073734', // This should be on the account object in Redux
  displayName: 'John Doe',
  avatar: `data:image/png;base64,${result.data}`
}

channel.send({ event: 'account:update', payload })
```

**Comment by Ellobo16** [comment]
**11/01/2022 Testing Results**

@suleymanCel @vitalikgriza 

- Current subscription plan not displaying under the email address
