### ISSUE TITLE
[Contacts] Add Contacts Screen

### ISSUE THREAD

**Issue by hexadecible** [Telios-org/rn-mobile-client#40]
Create a screen to manage users' contacts. User's should have the ability to create, edit, and delete contacts from this screen. There are no Figma mockups for this screen so please mimic the styles used for desktop as close as possible.

- [x] Create a list of contacts sorted alphabetically by the last name. If the last name does not then sort by the first letter of the contact's email address.
- [x] Create a group separator/divider for each letter of the alphabet when displaying the contact list. The letter should be displayed and capitalized inside the divider for each group.
- [x] Enable the ability to search for each contact.
- [x] Add the ability to create a new contact
- [x] Add the ability to edit each contact
- [x] Add the ability to remove each contact
- [x] Selecting each contact should show a contact detail screen.
- [x] Contact detail screen should show the contact's avatar, first/last name (if first and or last name does not exist, then use the contact's email address), Nickname, birthday, email, website, address, phone, organization, title, and notes.

#### Contacts API
[https://github.com/Telios-org/telios-client-backend#contacts-api](https://github.com/Telios-org/telios-client-backend#contacts-api)

![Screen Shot 2022-08-19 at 9 59 10 AM](https://user-images.githubusercontent.com/63071090/185635234-c5fde9ff-d811-415a-8abb-774d3bbb96a1.png)

**Comment by Ellobo16** [comment]
**11/01/2022 Testing Results**

@suleymanCel 

- Searching for contacts does not work
<img src="https://user-images.githubusercontent.com/114693640/199281386-5b01ffaa-add0-450f-b1fc-865ad3177a40.jpg" height="200" width="175">



- Contact list should be sorted in the following order: (1) First Name (2) Last Name (3) Email
<img src="https://user-images.githubusercontent.com/114693640/199349319-47849ff4-d585-474e-b843-79d9dfbb997a.jpg" height="350" width="175">

- Also take a look at the size of the circle and padding for the avatar

**Comment by Ellobo16** [comment]
@suleymanCel the majority of this ticket passes. The search still didn't work in the latest TestFlight. I opened a ticket specifically for that. I propose we close this one and use that one to get the search tested and done.
