### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by Poussinou** [Telios-org/rn-mobile-client#45]
Hi,

Since this app is FLOSS, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind.

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app in F-Droid by yourself, would you still agree with the inclusion of your app in F-Droid by the maintainer team?

Could you please in the meantime tag your [releases](https://github.com/Telios-org/rn-mobile-client/releases) and attach a signed release apk to it, so that people can easily download your app?

**Comment by ynnelson** [comment]
Hey Poussinou,

We haven't released the app for beta consumption yet but when we do release it we will have the binaries posted.
As far as the F-droid inclusion, it probably won't be something we do right out of the gate. Now if the maintainer team wants to handle it, I don't think we'd be opposed to it.
