### ISSUE TITLE
Can't go back to login screen from consent screen

### ISSUE THREAD

**Issue by ynnelson** [Telios-org/rn-mobile-client#49]
![IMG_2834C64A9313-1](https://user-images.githubusercontent.com/9703315/191148626-7169a9d1-2ff8-46ab-94dd-d7ab5d515669.jpeg)

As seen above when on beta consent screen it is impossible to return to login screen.
There should be a back arrow to go back to login screen.

**Comment by Ellobo16** [comment]
Passed testing 11/21/2022
