### ISSUE TITLE
Delete Messages

### ISSUE THREAD

**Issue by hexadecible** [Telios-org/rn-mobile-client#52]
Users should have the ability to move email messages to the Trash and then ultimately remove those messages permanently from the database and decentralized storage.

Initially moving an item to the Trash folder happens on two separate screens.

1. In the list view, the user should have the ability to swipe left on the email row to move this message to the trash folder. (see attached) 
```js
const emails = emailArr.map(msg => {
  return {
    ...msg,
    folder: { // Add this object to each email with the ID of the folder the email is moving to
      toId: 4 // Trash
    }
  }
})

const payload = {
  messages: emails
}

channel.send({ 
    event: 'email:moveMessages', 
    payload
})
```

2. In the message display view selecting the trash icon in the top left corner should also move this message to the trash. 

When an email is deleted from the Trash folder, it should then be permanently deleted
```js
channel.send({ 
    event: 'email:removeMessages', 
    payload: { messageIds: [emailId] }
})
```

![Screen Shot 2022-09-28 at 10 20 34 AM](https://user-images.githubusercontent.com/63071090/192804997-4fab34c5-134e-417d-8b0d-65b2aebdfdc4.png)

**Comment by Ellobo16** [comment]
**11/01/2022 Testing Results**

PASS
