### ISSUE TITLE
Fix recovery password flows

### ISSUE THREAD

**Issue by vitalikgriza** [Telios-org/rn-mobile-client#85]
- [x] Need to test recovery by passphrase flow
- [x] Finalise implementation of Recovery by code flow

**Comment by Ellobo16** [comment]
@vitalikgriza the recovery via passphrase works, but I cannot test the recovery email route. Is this because it's in the dev environment?

**Comment by Ellobo16** [comment]
Passed testing 11/22/2022

* We cannot test the recovery email in the dev environment, but the passphrase recovery worked.
